#! /bin/bash
# Test si argument (adresse) présent
presArg=${1:?"Vous devez fournir l'adresse à atteindre en argument."}

#rawU=$(traceroute -n  $presArg| sed 's/*/#/g' | sed 's/$/\\n/g');
#rawT=$(traceroute -n  $presArg| sed 's/*/#/g' | sed 's/$/\\n/g');
rawI=$(traceroute -n -I $presArg| sed 's/*/#/g' | sed 's/$/\\n/g');
declare -a meth=("-U -p 53" "-T -p 443" "-T -p 22" "-T -p 25" "-T -p 80");
compteur=0;
# Test si machine accessible
#ping -c1 $presArg >> /dev/null;
#if  [[ $? == 0  ]] ; then
#	echo "La machine $presArg est accessible, tests en cours ..."
#	if ! [ $(echo -e $rawI  | grep "\#")  ]
#	then
#		echo "La machine est accessible directement en ICMP "
#		echo -e  $rawI
#	fi
#else 
#	echo "La machine $presArg n'est pas accessible"
#	exit 1
#fi



# Début du code utile
for compteur in $(seq 1 30); do
	
	for i  in "${!meth[@]}"; do
		
		tr=$(sudo traceroute -n -f $compteur -m $compteur ${meth[i]} $presArg|tail -n 1|awk '{print $2}')
		echo -e "$tr"

		if  echo $tr |awk '{print $1}'| grep "*" ; then
			
			echo "Méthode employée: ${meth[i]}"
		       	if [ $opt -eq 5 ]
		       	then
				echo $opt
		 		echo "Le routeur n°$compteur ne répond pas"		
				compteur=$(($compteur+1));
				break;
			fi
		fi
	done 
done	
